#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := tinyLidar.cpp HCSR04.cpp piezo.cpp cBall.cpp cPaddel.cpp pongManger.cpp controler.cpp YL40.cpp GY61.cpp potmeter.cpp

# header files in this project
HEADERS := tinyLidar.hpp HCSR04.hpp piezo.hpp cBall.hpp cPaddel.hpp pongManger.hpp controler.hpp YL40.hpp GY61.hpp potmeter.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
